version: "3.5"
services:
  master:
    image: tcimba/hadoop-cluster:latest
    container_name: hadoop-master
    hostname: hadoop-master
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: hdfs-data
        target: /usr/local/hadoop/hdfs/data
      - type: volume
        source: logs
        target: /usr/local/hadoop/logs
      - type: bind
        source: ${SHELL_FOLDER}/workers
        target: /usr/local/hadoop/etc/hadoop/workers
    ports:
      - "9870:9870"
      - "8088:8088"
      - "19888:19888"
    networks:
      - hadoop-net
networks:
  hadoop-net:
    driver: overlay
    external:
      name: hadoop-net
volumes:
  hdfs-data:
  logs:
