version: "3.5"
services:
  worker:
    image: tcimba/hadoop-cluster:latest
    container_name: hadoop-worker-${WORKER_ID}
    hostname: hadoop-worker-${WORKER_ID}
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: hdfs-data
        target: /usr/local/hadoop/hdfs/data
      - type: volume
        source: logs
        target: /usr/local/hadoop/logs
      - type: volume
        source: zookeeper-data
        target: /usr/local/zookeeper/data
#      - type: bind
#        source: ${CONFIG_FOLDER}/zoo.cfg
#        target: /usr/local/zookeeper/conf/zoo.cfg
    networks:
      - hadoop-net
    command: ${WORKER_NUMBER} ${WORKER_ID}
networks:
  hadoop-net:
    driver: overlay
    external:
      name: hadoop-net
volumes:
  hdfs-data:
  logs:
  zookeeper-data:
