version: "3.5"
services:
  worker:
    image: hadoop-cluster:latest
    container_name: hadoop-worker-${WORKER_ID}
    hostname: hadoop-worker-${WORKER_ID}
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: hdfs-data
        target: /usr/local/hadoop/hdfs/data
      - type: volume
        source: logs
        target: /usr/local/hadoop/logs
    networks:
      - hadoop-net
networks:
  hadoop-net:
    name: hadoop-net
    driver: bridge
volumes:
  hdfs-data:
  logs:
